### ISSUE TITLE
Last element is link too!

### ISSUE THREAD

**Issue by link-er** [weppos/breadcrumbs_on_rails#29]
Hello
After update to 2.2.0 I found that the last element in breadcrumbs chain (current page) is generated as link.
Maybe something wrong?

**Comment by araslanov-e** [comment]
I have not installed `gem twitter-bootstrap-rails`, but last element is link too. What me do?

**Comment by borwahs** [comment]
I am having this problem when I have a URL parameter that has a different case.

For example:

`/collections/all/1` renders without the last element as a link.
`/collections/All/1` renders with the last element as a link.

**Comment by borwahs** [comment]
The issue comes down to the `link_to_unless_current` method used by this gem. Since I used two different ways to generate the URL in my views, I noticed the difference in the URL. It doesn't look like `link_to_unless_current` ignores case (which is probably the right call).

I resolved this by checking the `collection_piece_type` param in my controller action to see if it contains any uppercase characters. If it does, I convert the specific param to lowercase and call `redirect_to` with the all lowercase version. It did not require any changes to this gem.

See [ActionView::Helpers::UrlHelper.link_to_unless_current](http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html).
