### ISSUE TITLE
Adding a parent crumb?

### ISSUE THREAD

**Issue by rhnorment** [weppos/breadcrumbs_on_rails#68]
Thanks for the great work!

If I have Pages controller for static web pages which have a navigation hierarchy, can I force the parent link to exist somehow?

```
pages_controller

def about
   add_breadcrumb  'About us', :about_path
end

def leadership
   add_breadcrumb  'Leadership', :about_leadership_path
end
```

The routing works fine, but the breadcrumbs do not render according to the routes.  Could I do something like this?

```
pages_controller

def about
   add_breadcrumb  'About us', :about_path
end

def leadership
   add_breadcrumb  'Leadership', :about_leadership_path, options: { parent_path: :about_path }
end
```

Thanks in advance.

**Comment by weedySeaDragon** [comment]
I've solved this by using an abstract parent class controller that sets the parent link.  The controller for the page is a subclass of that abstract parent class controller.  The abstract parent controller sets the parent breadcrumb using `before_action: { add_crumbs :section_parent_path, t('breadcrumbs.parent_section_crumb') }`  and then the child controller sets it's own crumb :  `before_action: { add_crumbs :this_page_path, t('breadcrumbs.this_page_crumb') }`  
The `before_action` in the abstract parent class controller is called first, so that breadcrumb is added before the child controller ("this page").

Your example could be set up like this:
```
class AboutUsSectionController < ApplicationController
     before_action: { add_crumbs :about_path, t('breadcrumbs.about_us) }
    ...
  end

class LeadershipPagesController < AboutUsSectionController 
   before_action: { add_crumbs :about_leadership_path, t('breadcrumbs.leadership) }
  ...
end
```
Then the result would be:
**Home / About Us / Leadership**

(assuming, of course, those are the entries in your I18n .yml file)

Just one way to do it.  (Perhaps concerns would also work.) I have other reasons to also have a parent controller class, so was a reasonable approach for me.

**Comment by rhnorment** [comment]
Nice!.  Thank you.
