### ISSUE TITLE
undefined method `html_safe' for {:separator=>""}:Hash

### ISSUE THREAD

**Issue by inyerade** [weppos/breadcrumbs_on_rails#69]
I need change the separator but I get the error:

```
undefined method `html_safe' for {:separator=>""}:Hash
```

I use in view 

```
<%= render_breadcrumbs :separator => "" %>
```

If I use 

```
<%= render_breadcrumbs %>
```

all OK

**Comment by manelpb** [comment]
Try to use like this way: 

`<%= render_breadcrumbs("  ", { class: '', item_class: '', divider_class: '', active_class: 'active' })  %>`

**Comment by inyerade** [comment]
thx @manelpb solve the problem. but I think is no a clean solution

**Comment by marlonmantilla** [comment]
Having the same issue, @manelpb your solution didn't work out for me now I'm getting ` wrong number of arguments (2 for 0..1) `

**Comment by 4itosik** [comment]
I had a same problem `wrong number of arguments (2 for 0..1)`, when I update `rails` to `4.2.4`

**Comment by frcake** [comment]
same problem here :S anything ?

**Comment by cesswairimu** [comment]
using your solution  @manelpb it removes the 'html_safe' error but the default '/' for separator still remains. Any solution

**Comment by loyaruarutoitsu** [comment]
@cesswairimu Aparently this bug isn't due to breadcrumbs_on_rails.
All people having this bug check if you are using the gem 'twitter-bootstrap-rails' as well. That gem has a method with the same name 'render_breadcrumbs'. However it doesn't expect a hash as parameter.

You either have to deinstall the gem 'twitter-bootstrap-rails' or it will collide with this gem.
I suggest this bug is closed.

**Comment by cesswairimu** [comment]
Hey @loyaruarutoitsu, yeah it can be closed. I somehow fixed my prob (Can't recall how though :see_no_evil: ) but yeah I see what you mean. Thanks
