### ISSUE TITLE
Please pass on mainterership

### ISSUE THREAD

**Issue by jcoyne** [weppos/breadcrumbs_on_rails#90]
Are you done maintaining this gem?  Would you please consider passing it to someone who will continue to maintain it?

breadcrumbs_on_rails is a dependency of our Spotlight project. So we at https://github.com/projectblacklight would be willing to take it up, if you are willing to transfer it to us.

**Comment by weppos** [comment]
@jcoyne I admit I have limited time these days, but frankly so far the contributions I received were almost always missing tests, and addressing specific user's desires rather than trying to think in terms of a maintainer of a library.

I'd be happy to share the maintenance or pass it, but I'd wish to find someone that can demonstrate to maintain a reasonable level of quality of the contributions.

So far, the only major big issue is compatibility with Rails 5. But among all the various tickets and patches, no one provided a real fix supported by a test suite.

**Comment by jcoyne** [comment]
@weppos Okay, I saw a few open PRs, but I admit I didn't look to see that you were still commenting on those. 👍
